### PR TITLE
Enable building and use of this package on illumos-based operating systems

### PR DESCRIPTION
**Pull request by szaydel**
Thank you for considering this PR. I built the `zstd` library on a recent version of the OmniOS, which is an illumos-based operating system and included it with the tweak modeling already existing examples. I went ahead and confirmed that the package builds correctly, and I am able to leverage it in `VictoriaMetrics`, which depends on it.

### CODE REVIEW

**Comment by szaydel** [comment]
I just wanted to bump this request and see if there is anything more I can do to help move this forward. Thanks!

**Comment by szaydel** [comment]
Good day, I wanted to follow-up and see why there seems to be acknowledgement or feedback. If this is inappropriate for any reason, please do let me know. If you would like this updated since the PR is now stale, I am happy to do that. Any feedback would be better than nothing.

Thank you, Sam.

**Comment by valyala** [comment]
@szaydel , thanks for the pull request!

**Comment by valyala** [comment]
Sorry for the delay with the merge.

**Comment by szaydel** [comment]
@valyala , no problem at all with this. I am sure there is a lot on your plates. I appreciate it!

**Pull request merged**
