### PR TITLE
 Update upstream zstd from v1.4.2 to v1.4.3

### PR DESCRIPTION
**Pull request by zhuyie**

### CODE REVIEW

**Comment by valyala** [comment]
Thanks!

**Comment by denisgolius** [comment]
Hey @zhuyie , can you describe the build process for `libzstd_windows_amd64.a` or point me to some how-to to make the new one?

**Comment by zhuyie** [comment]
@denisgolius 
1. download & install TDM64-GCC: https://github.com/jmeubank/tdm-gcc/releases/download/v10.3.0-tdm64-2/tdm64-gcc-10.3.0-2.exe
2. download & install GnuWin32-make: https://gnuwin32.sourceforge.net/downlinks/make.php
3. download & install CMake: https://github.com/Kitware/CMake/releases/download/v3.26.3/cmake-3.26.3-windows-x86_64.msi
4. cd gozstd\zstd\cmake
5. mkdir out
6. cd out
7. cmake .. -DZSTD_BUILD_SHARED=OFF -DZSTD_BUILD_PROGRAMS=OFF -G "MinGW Makefiles"
8. make
9. copy lib/libzstd.a ../../../../libzstd_windows_amd64.a

**Comment by denisgolius** [comment]
> @denisgolius
> 
>     1. download & install TDM64-GCC: https://github.com/jmeubank/tdm-gcc/releases/download/v10.3.0-tdm64-2/tdm64-gcc-10.3.0-2.exe
> 
>     2. download & install GnuWin32-make: https://gnuwin32.sourceforge.net/downlinks/make.php
> 
>     3. download & install CMake: https://github.com/Kitware/CMake/releases/download/v3.26.3/cmake-3.26.3-windows-x86_64.msi
> 
>     4. cd gozstd\zstd\cmake
> 
>     5. mkdir out
> 
>     6. cd out
> 
>     7. cmake .. -DZSTD_BUILD_SHARED=OFF -DZSTD_BUILD_PROGRAMS=OFF -G "MinGW Makefiles"
> 
>     8. make
> 
>     9. copy lib/libzstd.a ../../../../libzstd_windows_amd64.a

Thanks!

**Pull request merged**
